### ISSUE TITLE
getPixel error in Python 3.4

### ISSUE THREAD

**Issue by gdweber** [bnmnetp/cImage#2]
Some students and I are encountering this sort of error with cImage and Python 3.4, but not in Python 3.2:

$ python3
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cImage
>>> e = cImage.EmptyImage(300, 300)
>>> e.getPixel(0, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gdweber/.local/lib/python3.4/site-packages/cImage.py", line 310, in getTkPixel
    p = [int(j) for j in self.im.get(x,y).split()]
AttributeError: 'tuple' object has no attribute 'split'

After looking into the source code of cImage.py a little, I thought that installing Pillow would help, but it doesn't.  It seems that there is also an error importing (part of) PIL:

>>> cImage.pilAvailable
False
>>> from PIL import Image as PIL_Image
>>> from PIL import ImageTk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'ImageTk'
>>> 

Those of us encountering the error are using recent versions of Ubuntu.  In my case it's Lubuntu 14.04.1 LTS, Python 3.4.0, and python3-pil 2.3.0-1ubuntu3.

**Comment by embarnard** [comment]
If you remove the ".split()" it should work. It's odd, for some of my students' computers the .split() is necessary, and for others it's necessary to *not* have the .split(). We can't seem to find a pattern regarding Python version.

**Comment by bnmnetp** [comment]
This should actually have been fixed by PR #4, submitted a few weeks ago.  Have you tried using the latest cImage.py from this repository?   I should have closed this issue when I accepted the PR, but it would be nice to have confirmation from another source.

Brad

**Comment by gdweber** [comment]
I no longer have Python 3.4.0, but the current version of cImage works (that is, does not have this error) in Python 3.5.0 on Manjaro Linux; it works in Python 3.4.3 on Ubuntu 14.04.3 LTS; and it still works in Python 3.2 on Red Hat Enterprise Linux 6.7.

Sorry for my delayed response; cImage gets my attention seasonally, according to my teaching schedule, and the season is here again!
